### ISSUE TITLE
Thank you for clean and easy to use GUI (and 2 issues :)

### ISSUE THREAD

**Issue by JFMugen** [Tenpi/Waifu2x-GUI#1]
I really loved how clean it is. 

But looks like it doesn't work on video files. I tried with both mp4 and webm but both of them failed. It creates the image folder and upscale images, but then it fails to create video again. GIF works tho. 

And one more issue/request, can we have an option to put files near original ones instead of a single folder? I think it would be lot better overall.

**Comment by Tenpi** [comment]
I added an option to use the same directory as the source image -> `v0.2.6`

You need to provide an example of a video that doesn't work, because all of the videos I've tried worked for me. Please trim it to a short length so it doesn't take forever to upscale.

**Comment by JFMugen** [comment]
Thanks for the update ^^ 

I attached a video, it is just 3 seconds long. Looks like it creates Temp.mp4, but then it stops. It looks like "Finished" in GUI as well. 

https://user-images.githubusercontent.com/61559703/159669460-64a7bfa5-0616-4ede-8124-0df239260ca2.mp4

**Comment by Tenpi** [comment]
Hi, the bug should be fixed in this version -> `v0.2.7`. 

It was using globally installed ffmpeg instead of the ffmpeg that I bundled with the app for the final encode, so if you didn't have ffmpeg installed it would fail. 

The `temp.mp4` is the raw output of combining all of the upscaled frames and audio. Sometimes this is longer than the original video, such as when the fps is a fraction like `29.97`, so I encode the video again to adjust for this.

**Comment by JFMugen** [comment]
> It was using globally installed ffmpeg instead of the ffmpeg that I bundled with the app for the final encode, so if you didn't have ffmpeg installed it would fail.

I am just curious, the ffmpeg you include is different from "global" one that we can download from their website?

**Comment by Tenpi** [comment]
> > It was using globally installed ffmpeg instead of the ffmpeg that I bundled with the app for the final encode, so if you didn't have ffmpeg installed it would fail.
> 
> I am just curious, the ffmpeg you include is different from "global" one that we can download from their website?

It's the same ffmpeg, but it might be an older version. I'm not really going to update it everytime they release a new version.

If you want to use globally installed ffmpeg, go to the location that the app is installed and delete the whole ffmpeg folder. It should automatically use the globally installed ffmpeg and it will save you ~40MB of storage space.

**Comment by JFMugen** [comment]
Got it, thank you for answer and the updates (and the app :)

**Comment by JFMugen** [comment]
@Tenpi Looks like "Source Directory" isn't persistent, and you need to choose it again every time you launch the program. 

Not a huge deal, but I think it should be persistent.

**Comment by Tenpi** [comment]
Hi, it should be persistent in this version -> `v0.2.8`
