### ISSUE TITLE
W2X shows its upscaling but it does not save the images - ergo - cannot create upscaled video

### ISSUE THREAD

**Issue by stinkybread** [Tenpi/Waifu2x-GUI#10]
After it's 1st run - the app creates the images and creates the folder for saving upscaled images but does not actually save them in the folder. When it then finishes upscaling per the app, it obviously cannot find any upscaled images in that folder and throws an error message
<img width="799" alt="Screenshot 2023-05-06 at 9 38 58 PM" src="https://user-images.githubusercontent.com/22078798/236635067-2b27abe8-f092-404c-a32d-7ad0ce2b48f1.png">

Note that this error persists across version till the latest one. I am running a Macbook Pro M1 Pro 
.

**Comment by Tenpi** [comment]
On Mac you have to compile it from source because it relies on external dependencies and the version I compiled might be old (I have no plans to constantly update it).

https://github.com/Tenpi/Waifu2x-GUI#macos 

Alternatively, switch to the ESRGAN upscaler, which is faster and produces better results. Only limitation is that scaling is limited to the range 2-4.

**Comment by stinkybread** [comment]
Thanks you for your comment.

**Comment by JFMugen** [comment]
@Tenpi I am having this issue on Windows as well. Looks like it works on Real-Esrgan, but on Waifu2X it doesn't create upscaled images and give the same error. 

Personally I don't think Real-Esrgan is good enough for details as well :/

**Comment by stinkybread** [comment]
@JFMugen - You can alternatively pursue other applications, more custom built like https://github.com/chaiNNer-org/chaiNNer - Here you can possibly use a wider range of models. Not as easy as W2X but gets it done on a mac.

**Comment by JFMugen** [comment]
> @JFMugen - You can alternatively pursue other applications, more custom built like https://github.com/chaiNNer-org/chaiNNer - Here you can possibly use a wider range of models. Not as easy as W2X but gets it done on a mac.

I am mainly using for videos, and not many offers that. (I guess I can do it with ffmpeg myself but lazy :)

**Comment by Tenpi** [comment]
@JFMugen If a Windows update broke waifu2x cpp there's not much I can do. I don't maintain that software and it was abandoned. You can try finding a different model and I will see if I can add it. Preferably it should be an executable file, I'm not sure if you can run a python model on my codebase. 

@stinkybread it does work on mac (I'm a mac user) you just have to compile it. If you are still interested I could write more detailed instructions.
