### ISSUE TITLE
Failed to run AppImage

### ISSUE THREAD

**Issue by IcteFourU** [Tenpi/Waifu2x-GUI#12]
Error in GUI:
A JavaScript error occurred in the main process

Uncaught Exception:

Error: EROFS: read-only file system, chmod '/

tmp/.mount_Waifu2BswDij/ffmpeg/ffmpeg at Object.chmodSync (fs.js:1320:3)

at App.<anonymous> (/tmp/.mount_Waifu2BswDij/resources/ app.asar/dist/main.js:233:15466) at App.emit (events.js:376.20)

Error in terminal:
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

OS: Garuda

**Comment by Tenpi** [comment]
The program needs to be given write permissions over your filesystem.

**Comment by Simon1511** [comment]
> The program needs to be given write permissions over your filesystem.

A little explanation on this would be helpful as I'm facing the same issue.

**Comment by Tenpi** [comment]
> A little explanation on this would be helpful as I'm facing the same issue.

Sorry I don't use linux but the error is self-explanatory. The program doesn't have permissions to write to your file system. I would look up online how to give writing permissions to a program for the OS you're using.

**Comment by Simon1511** [comment]
> > A little explanation on this would be helpful as I'm facing the same issue.
> 
> Sorry I don't use linux but the error is self-explanatory. The program doesn't have permissions to write to your file system. I would look up online how to give writing permissions to a program for the OS you're using.

I already know what "Permission denied" means. What bugs me is that the AppImage wants permission to write to /, which it definitely shouldn't be granted.
Apart from that, as far as I'm aware (and from what I could find on the internet) it's not possible to simply grant permissions to an AppImage.
And changing permissions/ownership of / is something that definitely shouldn't be required for a simple AppImage.

Anyway, I found a better tool that runs on Linux and doesn't require me to give it all kinds of permissions.
