### ISSUE TITLE
 can not pnpm run start+

### ISSUE THREAD

**Issue by ShuangDa1018** [Tenpi/Waifu2x-GUI#14]
> waifu2x-gui@0.4.1 clean
> del-cli ./dist

/home/shuang/Desktop/github/electron/Waifu2x-GUI/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:146
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)

**Comment by Tenpi** [comment]
Install `del-cli`, or remove it and delete dist folder manually if you can't.
