### ISSUE TITLE
a javascript error occurred in the main process

### ISSUE THREAD

**Issue by zkr6rc2iny** [Tenpi/Waifu2x-GUI#16]
could you check this please 
![error](https://github.com/Tenpi/Waifu2x-GUI/assets/138602857/9ab42c93-0221-4641-99bb-bb50ca615307)

**Comment by Tenpi** [comment]
Please redownload `v0.4.2` (I replaced the file). Looks like I have to build on a windows vm

**Comment by zkr6rc2iny** [comment]
@Tenpi Thank you, it's working normally now I wanted to know if there is a way to use other models like NMKD UltraYandere Lite and 4x_NMKD-UltraYandere_300k and among other models you could add this option in the next updates pls

**Comment by Tenpi** [comment]
No support for PyTorch models yet but I can look into it, you will have to have python installed separately though. Please start a different issue for that to track it.

**Comment by zkr6rc2iny** [comment]
@Tenpi I already have Python installed and a bug in upscaler Waifu2x it doesn't finish the image it appears
![Sem título](https://github.com/Tenpi/Waifu2x-GUI/assets/138602857/bc972337-823e-4a4a-93e8-1551f1462765)

**Comment by Tenpi** [comment]
Update to `v0.4.3` you can add custom esrgan models to the "models" folder where the app is installed. I also added real-cugan and changed the waifu2x version

**Comment by zkr6rc2iny** [comment]
@Tenpi sorry I'm a little boring + could you act on the next update to upscale 8x and 16x if possible pls does not work or is not activated 
![fsfdsdf](https://github.com/Tenpi/Waifu2x-GUI/assets/138602857/8cf57232-3173-4df0-9c23-a8c53f631a90)

**Comment by Tenpi** [comment]
waifu2x just repeats the 2x scale multiple times to get the desired scaling. If it doesn't work with 8x and 16x do 4x*2x or 4x*4x scaling consecutively it should have the same result.

**Comment by zkr6rc2iny** [comment]
@Tenpi Good morning friend + once the models are not working AnimeSharp and UltraYandere 
![12344f](https://github.com/Tenpi/Waifu2x-GUI/assets/138602857/6ca1fa0a-39cf-4659-97aa-785a43882166)

**Comment by Tenpi** [comment]
try again if not install the dependencies required for the python script
```
pip install torch torchvision numpy opencv-python spandrel Pillow
```

**Comment by zkr6rc2iny** [comment]
@Tenpi another bug again 
![48133516](https://github.com/Tenpi/Waifu2x-GUI/assets/138602857/e8747c45-c838-4501-8d86-3e030c7d2ab0)

**Comment by Tenpi** [comment]
try redownloading it again
