### ISSUE TITLE
macOS up doesn't work

### ISSUE THREAD

**Issue by DoctorRyner** [Tenpi/Waifu2x-GUI#17]
Since v0.4.6 it says the app is broken and cannot be started

**Comment by Tenpi** [comment]
It's not signed (you have to pay $100/yr). You have to remove the quarantine flag to open.
```
xattr -d com.apple.quarantine /Applications/Waifu2x\ GUI.app
```

**Comment by DoctorRyner** [comment]
Oh, thanks
