### ISSUE TITLE
DiscardVirtualMemory procedure not found

### ISSUE THREAD

**Issue by yurofeng** [Tenpi/Waifu2x-GUI#22]
when i install versions 0.4.3 and up (would probably be the same for 0.4.2). 0.4.1 works fine.
windows 8.1.
i think you ended up breaking it for 8.1. you can probably add a note somewhere that it requires win10.
will have to use something else.

**Comment by Tenpi** [comment]
The newer electron versions dropped support for all windows versions older than 10 but I will try downgrading back again.

**Comment by Tenpi** [comment]
It should work again in v0.5.0

**Comment by yurofeng** [comment]
you're too cool, thanks.
your app's drag and drop workflow is very nice so it's tough to switch.
