### ISSUE TITLE
[Suggestion] Little preview shows progress instead of looping the input video

### ISSUE THREAD

**Issue by JFMugen** [Tenpi/Waifu2x-GUI#3]
Wouldn't it be better if it would just show the currently processed frame to show progress?

**Comment by Tenpi** [comment]
I might change it when I have time but its not a priority

**Comment by JFMugen** [comment]
> I might change it when I have time but its not a priority

Sure, that's just an improvement idea.

**Comment by Tenpi** [comment]
Added
