### ISSUE TITLE
Request for Linux adaptation.

### ISSUE THREAD

**Issue by ngdngdc** [Tenpi/Waifu2x-GUI#4]
Can you provide support for Linux? As an electron application, this should not create much difficulty.

**Comment by Tenpi** [comment]
Will you mind compiling a version of `waifu2x-converter-cpp` for Linux? I am on a Mac with ARM architecture, so I can only compile for ARM Linux, not the x64 Linux that most people use.

https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md#linux 

Open a pull request in this repository that adds the linux compiled version
https://github.com/Tenpi/waifu2x 

If you don't want to compile waifu2x, I could just make it work only with Real-ESRGAN on Linux.

**Comment by ngdngdc** [comment]
> Will you mind compiling a version of `waifu2x-converter-cpp` for Linux? I am on a Mac with ARM architecture, so I can only compile for ARM Linux, not the x64 Linux that most people use.
> 
> https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md#linux
> 
> Open a pull request in this repository that adds the linux compiled version https://github.com/Tenpi/waifu2x
> 
> If you don't want to compile waifu2x, I could just make it work only with Real-ESRGAN on Linux.

Sorry, the beignet that waifu2x depends on failed to compile on my device, so I may not be able to compile waifu2x-converter-cpp. But I found the archlinuxcn team compiled and packaged waifu2x and waifu2x-cuda in the [Arch Linux CN Community repo](http://repo.archlinuxcn.org/), and after unpacking you can get the binaries. I think this should work. Here is the [Arch Linux CN Community repo mirrors list](https://github.com/archlinuxcn/mirrorlist-repo).

**Comment by Tenpi** [comment]
Added linux version, let me know if it doesn't work.
