### ISSUE TITLE
Issue Installing (Can't open file for writing)

### ISSUE THREAD

**Issue by AyliasTheCoder** [Tenpi/Waifu2x-GUI#8]
![image](https://user-images.githubusercontent.com/79167674/231625274-d17d486f-5b57-4a68-97cc-ca60ee8c4860.png)
I get this error no matter where I try installing it to on windows 10 (Specifically Version 10.0.19045)

**Comment by Tenpi** [comment]
Run it as admin, looks like permission issue. You also may not have enough disk space to install it. The app will be around 500MB.

**Comment by AyliasTheCoder** [comment]
Turns out it was an issue with my antivirus
