### ISSUE TITLE
Webm doesn't complete conversion.

### ISSUE THREAD

**Issue by NanoAi** [Tenpi/Waifu2x-GUI#9]
When converting a webm file it creates all the upscaled images (for some reason in jpg, even if I specify no jpg compression), creates an MP4 file of the upscaled video and creates an unplayable webm file.

I'm assuming that the mp4 file is not getting correctly converted to webm?

**Comment by San3-Cod3** [comment]
'Munchy'roll-Downloader-Setup-0.6.2.exe; a similar GUI application to this, which was released on Softpedia also, has broken indefinitely due to Cloudfare anti-bot measures, I assume.  Sorry to hi-jack this; just needed to alert creator.  Alternatives are YT-DLP or multi-downloader-nx, but this GUI front-end app was really, really nice.  It would be great if it could get a fix as the other alternatives I mentioned do still work, but aren't as cute or cool as these GUIs are.

**Comment by Tenpi** [comment]
> When converting a webm file it creates all the upscaled images (for some reason in jpg, even if I specify no jpg compression), creates an MP4 file of the upscaled video and creates an unplayable webm file.

Send me a short webm video with the problem. I do not believe I ever tested webm, file formats tested are: jpg, png, webp, gif, mp4

> 'Munchy'roll-Downloader-Setup-0.6.2.exe; a similar GUI application to this, which was released on Softpedia also, has broken indefinitely due to Cloudfare anti-bot measures, I assume.

Sorry, I am not interested in supporting Crunchyroll Downloader anymore because it is copyright infringement. (Meaning I could be sued).

**Comment by San3-Cod3** [comment]
> > When converting a webm file it creates all the upscaled images (for some reason in jpg, even if I specify no jpg compression), creates an MP4 file of the upscaled video and creates an unplayable webm file.
> 
> Send me a short webm video with the problem. I do not believe I ever tested webm, file formats tested are: jpg, png, webp, gif, mp4
> 
> > 'Munchy'roll-Downloader-Setup-0.6.2.exe; a similar GUI application to this, which was released on Softpedia also, has broken indefinitely due to Cloudfare anti-bot measures, I assume.
> 
> Sorry, I am not interested in supporting Crunchyroll Downloader anymore because it is copyright infringement. (Meaning I could be sued).

Hi, thanks for getting back - and I totally understand completely.  But is there any chance you have the source code still, and would be willing to share and let someone else work on it for themselves; even a kept-private version to work on if necessary? I wouldn't mind trying to improve on it under whichever terms - and respect it.

**Comment by Tenpi** [comment]
> Hi, thanks for getting back - and I totally understand completely. But is there any chance you have the source code still, and would be willing to share and let someone else work on it for themselves; even a kept-private version to work on if necessary? I wouldn't mind trying to improve on it under whichever terms - and respect it.

Sorry, I will no longer be supporting or distributing that software.

**Comment by NanoAi** [comment]
> Send me a short webm video with the problem. I do not believe I ever tested webm, file formats tested are: jpg, png, webp, gif, mp4

The video I was trying to upscale can be found here: https://gelbooru.com/index.php?page=post&s=view&id=7452061&tags=sakurada22

**Comment by Tenpi** [comment]
The problem isn't webm but specific to this video. I'm not sure what it is, low priority of fixing.

**Comment by NanoAi** [comment]
I'll look into it and see what's going on with that specific file. I have a
feeling it may not actually be a webm.

**Comment by NanoAi** [comment]
I checked the file, and the file headers, and the exif info; couldn't find anything specifically wrong with it.
Since it's just this specific webm, I'll close this issue. However maybe it's worth checking more webms over at safebooru and such.

I do however have a feeling that this file **is actually an mp4 file** that somehow got mangled into a webm, even obtaining the correct headers and exif info.

Video source: https://twitter.com/sakurada22/status/1367813275199578120
^ Various twitter video downloaders gave me an MP4 file, so I assume the original file is actually an MP4.

Maybe, it's worth adding some sort of check and giving a user a warning if a file they thought was one format... is actually a completely different format?

**Comment by Tenpi** [comment]
@San3-Cod3 Hi I updated the crunchyroll downloader but I think I will keep the repo private. But if you still want it you can contact me by email at itzmoepi@protonmail.com.
